[theme]
primaryColor = "#ff914c"    # "#575fe8" красный стандартный st
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#d9d9d9"   # c9eab8 серый стандартный st
# textColor = "#262730" 
# font = "serif"
